apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgCeEcZlwKS4gxGdNILOdJXrHtjsTdRvWy6ppKDWabm01ZR6oGYQwTfDFcpg1qRYOgHfo4gcbW8zeT9fAZTBqZqz8O1OxsEDoMkFTrAGDbNLH4FoN0bZ5rr8kEH0dpKzRnJINN7QiQiY4igbALj143hkG2rHLas4cIHlpxO7f3aeZPyI9XuaHQbLQGOPx5mAzjexkGwKE4PVIi07pozztRQfDEkapIm9Sl8eWFcqZI6rUU0dhIXJ4flEZyHATfnbX5/7gUFaVYAt1p8O+h5tCst9ZHp5nRoDAC4lHhYFjKgEo1vbCZb/btFtylhFVtAkYhAEXLEp+m0n0N1rqcG94iagXgp5uA/XxbMHMcMDG7evQJy1ilU59UIl9TnEE/GyS/z6rkayu9RDiZxi9vdOFFO0EeJwaJIMN1Mwpz3p+8zfRuVECwsj+jQL9UvnmDBJfIbmFcKk+k7/ZiF7TXfEuP1AbTq4eUkOg14Py49iI3Mkd4UqhYW5ULLAoy1lRr5bC53Y+n+0yslV3Fz/xJ5TbRdswHYUur6Jxaucc7npd9kclezslppCYDNVFbNTMYLTV8FVzDs/KTWmGta/DXxKTB4ZE/DNaZnx1EMWZP7p5RW8Mpouyo5x/xMWSEnzuc9rvv+oPhrF93PFRpZPlSVq0gKfa/OI6ua4d/heGGoK8+/fVumg5ibUrXvkq5XBpGPTISaxK2pR1ES7JnqzEbQ4BeXL7o2GmtI5GUrTVmVilqRAieXAca3kC6iLR11q7Pbj/JRCAHPNvCNGRCAM2eZgmV/eUQOvT0yuoEuVAeL0TLSRU/Q4udQoZ0NbrwmJkq/NqYJCbvlxyTSGAbRHs629IsfTucvLslZBzFntyjXXriKyV+EUTcHBVYDR5yVrRdgTs50HRXP8UWfGm2PraWRo/EBzYoP+U/p9efO6kv1YRZRSSF1b2qPXKSuqtLRTHXGbqx1Ss6h7KssJ27le9+erWQbeO3NxM0FjhCyBP+xNIv1KGSfFx+E8SHNortXw3ng8hPAWGHieHMLzMA4wFddJgA/l6ETnCFlt2VmUolCjpmjS/nO7AiacqNncoOJbp9zPpV8T6qjy04A4t5HfhY4eKHHNyvPjI8RaqHlrFwDSrARenSQ62821qwrXQXSgzrk9jIyCYrRBRVCfURn8/VJFn1vERMWI/Vjv6FsWJjekHf2BCD2Bce52kSAzi8m/zgCYSL9YYQpmFCAECApzmgwKSj9Yiu66X1x1Qlz9vtfWinWeOxG0w5+v95wS34AeMgJXZLBLbccbqW6ibecTiK/IJpbAjAMfbVpBfEqxbRVGipsInmOlM1QWhtezskm/E9rnstvw+91Xd3caj2znsq2mB4VPANKv4sTB5ljUg7Pl4j7krknpQLz/
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

